policy:
  - template: ['bug-report.yml', 'feature-request.yml', 'question.yml']
    section:
      - id: ['package']
        block-list: []
        label:
          - name: 'v1'
            keys: ['v1.x']
          - name: 'main'
            keys: ['main']
          - name: 'dev'
            keys: ['dev']
          - name: 'beta'
            keys: ['beta']
