packages:
  - ./
  - cli
  - playgrounds/nuxt
  - playgrounds/vue

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - puppeteer
  - sharp

ignoreWorkspaceRootCheck: true
